context:
  version: "6.4.3"
  maj_min: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: qt6-serialport
  version: ${{ version }}

source:
  url:
    https://download.qt.io/archive/qt/${{ maj_min }}/${{ version }}/submodules/qtserialport-everywhere-src-${{ version }}.tar.xz
  md5: cdc3fcb3e3180be16ee32fc3192b0a0c

build:
  number: 0
  skip:
    - osx and arm64
    - win

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: pkg-config
    - if: build_platform != target_platform
      then: qt6-main ${{ version }}.*
  host:
    - qt6-main ${{ version }}.*
    - if: linux
      then: libudev
  run:
    - qt6-main ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage('qt6-serialport', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - qt6/QtSerialPort/qserialport.h
        - qt6/QtSerialPort/qserialportglobal.h
      lib:
        - Qt6SerialPort

about:
  homepage: https://doc.qt.io/qt-6/qtserialport-index.html
  summary: Qt Serial Port support
  description: |
    Qt Serial Port provides basic functionality for configuration, I/O
    operations, and getting and setting the control signals of the RS-232
    pinouts.
  license: LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
  license_file: LICENSES/
  repository: https://github.com/qt/qtserialport
  documentation: https://doc.qt.io/qt-6/qtserialport-index.html

extra:
  recipe-maintainers:
    - multimeric
    - AndreFavotto
    - conda-forge/qt-main
  feedstock-name: qt6-serialport
